

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: ENC(6xq4yg92ePmlii2BBNB/l6cXolGGdt3Ul4zYi95gifdhHaPnq8/WCUsfFTgtJEs2yXdQ4Izc/7kT0sFnKvsUeA==)
    username: ENC(JDXj698sPbuxrNHAAf4Xwn0KgwXtaOY7)
    password: ENC(BAGrB5sDgIALDPL6U/ZzUUgBAaQYhqAe)

  security:
    user:
      password: 0000
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

## mapper logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info
    com:
      dejay:
        framework:
          mapper: trace
    ## Log Level Setting(default info)
    root: info

server:
  port: 3030

# file
file:
  rootDir: /files/dejay_public
  tempDir: /temp
  realDir: /upload