

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: ENC(R33IAvOz+1ctfKbKi5ja6Tf/emHrylzMOcLxQgyJVcgGyEUY9tJMuqjFDXE1KeWoi33TBYrj5KQ7fj9M4KPyaw==)
    username: ENC(IczFq75YIzNXTzSMeUHjBkK0Pcf8MXLN)
    password: ENC(TKuGEV/dnva+80V9kwB/gzGn89MyKQxz)

  security:
    user:
      password: 0000
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

## mapper logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info
    com:
      dejay:
        framework:
          mapper: trace
    ## Log Level Setting(default info)
    root: info

server:
  port: 8080

# file
file:
  rootDir: /files/dejay_public
  tempDir: /temp
  realDir: /upload