spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:tcp://localhost/~/framework
    username: sa
    password:

    hikari:
      maximum-pool-size: 4
      connection-test-query: SELECT NOW() FROM DUAL

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
server:
  port: 3000

## MyBatis
# mapper.xml 위치 지정
mybatis:
  mapper-locations:
    classpath:mappers/*.xml

  type-aliases-package: com.dejay.framework.vo
# set model property to camel case
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar

## mapper logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO
    com:
      dejay:
        framework:
          mapper: trace
## Log Level Setting(default info)
    root: warn