spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://10.34.220.168:3306/dejay_public
    username: dejay_was
    password: 22@dejay

    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT NOW() FROM DUAL

## mapper logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info
    com:
      dejay:
        framework:
          mapper: trace
## Log Level Setting(default info)
    root: info