spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/framework
    username: sa
    password:

    hikari:
      maximum-pool-size: 4

  h2:
    console:
      enabled: true
server:
  port: 3000

## MyBatis
# mapper.xml 위치 지정
mybatis:
  mapper-locations:
    classpath:mappers/*.xml

  type-aliases-package: com.dejay.framework.model.*
# set model property to camel case
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar

## mapper logging level
logging:
  level:
    com:
      dejay:
        framework:
          repository: TRACE