spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mariadb://10.34.220.168:3306/dejay_public
#    username: dejay_was
#    password: 22@dejay
    jdbc-url: ENC(7ArFwzUzPM6PT0CjSdzB1kpmpurrktH+mp5iW40azgtALCopmBQZLZTZRcY4fHLS+1rE5lVepYH3S85RsoOptQ==)
    username: ENC(IczFq75YIzNXTzSMeUHjBkK0Pcf8MXLN)
    password: ENC(TKuGEV/dnva+80V9kwB/gzGn89MyKQxz)

  security:
    user:
      password: 0000
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

## mapper logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info
    com:
      dejay:
        framework:
          mapper: trace
## Log Level Setting(default info)
    root: info

# file
file:
  rootDir: /files/dejay_public
  tempDir: /temp
  realDir: /upload