spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://10.34.220.168:3306/dejay_public
    username: dejay
    password: dejay@1234

## mapper logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info
    com:
      dejay:
        framework:
          mapper: trace
    ## Log Level Setting(default info)
    root: info

server:
  port: 3001