spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mariadb://10.34.220.168:3307/dejay_common
    username: dejay_was
    password: 22@dejay
  security:
    user:
      password: 0000
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    encoding: UTF-8
  mvc:
    static-path-pattern: "/static/**"
  devtools:
    livereload:
      enabled: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: dejayframework@gmail.com
    password: tvrx phxd gheh bcps
    properties:
      mail:
        debug: true
        mine:
          charset: UTF-8
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true

## mapper logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info
    com:
      dejay:
        framework:
          mapper: trace
    ## Log Level Setting(default info)
    root: info

server:
  port: 3030

# file
file:
  rootDir: classPath:files/dejay_public
  tempDir: /temp
  realDir: /upload