spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
server:
  port: 3000
  context-path: /
  encoding:
    charset: UTF-8
    enabled: true
    force: true

## MyBatis
# mapper.xml 위치 지정
mybatis:
  mapper-locations: classpath:mybatis-mappers/**/*Mapper.xml
  type-aliases-package: com.dejay.framework.vo
# set model property to camel case
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar

