spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mariadb://10.34.220.168:3307/dejay_common
    username: dejay_was
    password: 22@dejay

    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT NOW() FROM DUAL

  security:
    user:
      password: 0000

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
## mapper logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info
    com:
      dejay:
        framework:
          mapper: trace
## Log Level Setting(default info)
    root: error

server:
  port: 3030

# file
file:
  rootDir: /files/dejay_public
  tempDir: /temp
  realDir: /upload