INSERT INTO TEST(NAME) VALUES('TEST1');
INSERT INTO TEST(NAME) VALUES('TEST2');

INSERT INTO MEMBER(NAME, EMAIL) VALUES('John Doe', 'john@email.com');
INSERT INTO MEMBER(NAME, EMAIL) VALUES('Jane Doe', 'jane@email.com');