DROP TABLE IF EXISTS TEST;

CREATE TABLE TEST (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(100)
);